package docbank.app.telas;

import docbank.app.sql.DocbankDAO;
import docbank.app.func.Usuario;
import javax.swing.JOptionPane;

/**
* Classe da tela de login
* @author Mateus
* @version 1.0
* @since Primeira versão
*/
public class TelaDeLogin extends javax.swing.JFrame {

  private int idUsuarioLogado;
  private String nomeUsuarioLogado = "";
  private String emailUsuarioLogado = "";
  private String cargoUsuarioLogado = "";
  private final TelaInicial inicial;

  private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(TelaDeLogin.class.getName());

  /**
   * Creates new form TelaDeLogin
   *
   * @param inicial
   */
  public TelaDeLogin(TelaInicial inicial) {
    this.inicial = inicial;
    
    initComponents();
  }

  /**
   * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The content of this method is always regenerated by the Form Editor.
   */
  @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        campoEmail = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        botaoCancelar = new javax.swing.JButton();
        botaoEntrar = new javax.swing.JButton();
        campoSenha = new javax.swing.JPasswordField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Tela de Login");

        jLabel1.setFont(new java.awt.Font("Noto Sans", 1, 16)); // NOI18N
        jLabel1.setText("Email:");

        jLabel2.setFont(new java.awt.Font("Noto Sans", 0, 12)); // NOI18N
        jLabel2.setText("Email usado na criação da conta");

        jLabel3.setFont(new java.awt.Font("Noto Sans", 1, 16)); // NOI18N
        jLabel3.setText("Senha:");

        jLabel4.setFont(new java.awt.Font("Noto Sans", 0, 12)); // NOI18N
        jLabel4.setText("As senhas tem um mínimo de 8 caracteres");

        campoEmail.setFont(new java.awt.Font("Noto Sans", 0, 14)); // NOI18N
        campoEmail.setToolTipText("Digite seu email de login.");
        campoEmail.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.LOWERED));

        jLabel5.setFont(new java.awt.Font("Noto Sans", 1, 28)); // NOI18N
        jLabel5.setText("Login");

        botaoCancelar.setFont(new java.awt.Font("Noto Sans", 0, 14)); // NOI18N
        botaoCancelar.setText("Cancelar");
        botaoCancelar.setToolTipText("Cancelar login.");
        botaoCancelar.addActionListener(this::botaoCancelarActionPerformed);

        botaoEntrar.setFont(new java.awt.Font("Noto Sans", 0, 14)); // NOI18N
        botaoEntrar.setText("Entrar");
        botaoEntrar.setToolTipText("Entrar na conta.");
        botaoEntrar.addActionListener(this::botaoEntrarActionPerformed);

        campoSenha.setFont(new java.awt.Font("Noto Sans", 0, 14)); // NOI18N
        campoSenha.setToolTipText("Senha vinculada a conta cadastrada.");
        campoSenha.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.LOWERED));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(botaoCancelar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(botaoEntrar, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(100, 100, 100)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(campoSenha, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.CENTER)
                            .addComponent(campoEmail, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(100, 100, 100))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel5)
                .addGap(26, 26, 26)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(campoEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2)
                .addGap(26, 26, 26)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(campoSenha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 50, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(botaoCancelar)
                    .addComponent(botaoEntrar))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

  private void botaoCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoCancelarActionPerformed
    this.dispose();
  }//GEN-LAST:event_botaoCancelarActionPerformed

  private boolean autenticacao(String email, char[] senhaDigitada) {
    DocbankDAO dao = new DocbankDAO();
    Usuario usuario = dao.autenticarUsuario(email, senhaDigitada);
    java.util.Arrays.fill(senhaDigitada, '0');

    if (usuario != null) {
      this.idUsuarioLogado = usuario.getId();
      this.nomeUsuarioLogado = usuario.getNome();
      this.cargoUsuarioLogado = usuario.getCargo();
      this.emailUsuarioLogado = usuario.getEmail();
      return true;
    } else {
      JOptionPane.showMessageDialog(this, "Falha na autenticação.\nVerifique se suas credenciais estão corretas ou contate um administrador do sistema de sua organização para obter mais informações.");
      return false;
    }
  }

  private void botaoEntrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoEntrarActionPerformed
    String email = campoEmail.getText().trim();
    String regexEmail = "^[\\w-\\.]+@([\\w-]+\\.)+[\\w-]{2,4}$";
    char[] senha = campoSenha.getPassword();
    
    if (campoEmail.getText().isBlank() && senha.length == 0) {
      JOptionPane.showMessageDialog(null, "É necessário preencher todos os campos antes de prosseguir com o login.");
    } else if (campoEmail.getText().isBlank()) {
      JOptionPane.showMessageDialog(null, "O campo de Email encontra-se vazio. Por favor, preencha-o antes de prosseguir.");
    } else if (!campoEmail.getText().matches(regexEmail)) {
      JOptionPane.showMessageDialog(null, "Por favor, insira um e-mail válido (ex: nome@dominio.com).");
    } else if (senha.length == 0) {
      JOptionPane.showMessageDialog(null, "O campo de senha encontra-se vazio. Por favor, preencha-o antes de prosseguir.");
    } else if (senha.length < 8) {
      JOptionPane.showMessageDialog(null, "A senha deve ter pelo menos 8 caracteres.");
    } else {
      
      if (autenticacao(email, senha)) {
        inicial.configurarSessao(idUsuarioLogado, nomeUsuarioLogado, emailUsuarioLogado, cargoUsuarioLogado);
        JOptionPane.showMessageDialog(null, "Login efetuado com sucesso!\nBem-vindo(a) " + nomeUsuarioLogado + ".");
        this.dispose();
      }
    
    }
    java.util.Arrays.fill(senha, '0');
  }//GEN-LAST:event_botaoEntrarActionPerformed

  /**
   * @param args the command line arguments
   */
  public static void main(String args[]) {
    /* Set the Nimbus look and feel */
    //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
    /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
     */
    try {
      for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
        if ("Nimbus".equals(info.getName())) {
          javax.swing.UIManager.setLookAndFeel(info.getClassName());
          break;
        }
      }
    } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
      logger.log(java.util.logging.Level.SEVERE, null, ex);
    }
    //</editor-fold>
  }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botaoCancelar;
    private javax.swing.JButton botaoEntrar;
    private javax.swing.JTextField campoEmail;
    private javax.swing.JPasswordField campoSenha;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
